In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
# define the vocabulary size
voc_size = 10000

In [5]:
# one hot representation
one_hot_rep = [one_hot(words,voc_size) for words in sent]

In [6]:
one_hot_rep

[[4134, 2162, 4655, 8633],
 [4134, 2162, 4655, 3341],
 [4134, 839, 4655, 9649],
 [7915, 1473, 9348, 1230, 4962],
 [7915, 1473, 9348, 1230, 1489],
 [6481, 4134, 622, 4655, 9120],
 [6080, 8400, 6211, 1230]]

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np
import pandas as pd

In [10]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_rep, padding='pre',maxlen=sent_length)
print(embedded_doc)

[[   0    0    0    0 4134 2162 4655 8633]
 [   0    0    0    0 4134 2162 4655 3341]
 [   0    0    0    0 4134  839 4655 9649]
 [   0    0    0 7915 1473 9348 1230 4962]
 [   0    0    0 7915 1473 9348 1230 1489]
 [   0    0    0 6481 4134  622 4655 9120]
 [   0    0    0    0 6080 8400 6211 1230]]


In [11]:
# feature representation
dim = 10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

d:\anaconda3\envs\ann_env\Lib\site-packages\keras\src\layers\core\embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 243ms/step


array([[[ 0.03179053, -0.00409256, -0.00705085,  0.03885398,
         -0.04641166,  0.01878324,  0.01417912,  0.00223715,
          0.03637809, -0.01020919],
        [ 0.03179053, -0.00409256, -0.00705085,  0.03885398,
         -0.04641166,  0.01878324,  0.01417912,  0.00223715,
          0.03637809, -0.01020919],
        [ 0.03179053, -0.00409256, -0.00705085,  0.03885398,
         -0.04641166,  0.01878324,  0.01417912,  0.00223715,
          0.03637809, -0.01020919],
        [ 0.03179053, -0.00409256, -0.00705085,  0.03885398,
         -0.04641166,  0.01878324,  0.01417912,  0.00223715,
          0.03637809, -0.01020919],
        [ 0.02836977,  0.03812121,  0.0268068 , -0.03871166,
          0.000179  , -0.00920742,  0.00508385,  0.00823485,
         -0.0381976 ,  0.00997696],
        [ 0.00650861, -0.03719138,  0.033896  ,  0.04017265,
         -0.04747552, -0.02400612, -0.03725046,  0.01188666,
         -0.02356919,  0.04210656],
        [-0.02373685,  0.00066545, -0.00282389,  0.0

In [19]:
embedded_doc[0]

array([   0,    0,    0,    0, 4134, 2162, 4655, 8633])